// auth
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

// category listing 
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

// category wise products
export const CATEGORY_PRODUCT_REQUEST = "CATEGORY_PRODUCT_REQUEST";
export const CATEGORY_PRODUCT_SUCCESS = "CATEGORY_PRODUCT_SUCCESS";
export const CATEGORY_PRODUCT_FAIL = "CATEGORY_PRODUCT_FAIL";

// get all products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

// get single products
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";

// cart actions
export const ADD_QTY_ITEM = "ADD_QTY_ITEM";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const MINUS_QTY_ITEM = "MINUS_QTY_ITEM";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const SET_BASKET_ITEMS = "SET_BASKET_ITEMS";
export const SET_BASKET_MSG_ON = "SET_BASKET_MSG_ON";
export const SET_BASKET_MSG_OFF = "SET_BASKET_MSG_OFF";
export const GET_BASKET_TOTAL = "GET_BASKET_TOTAL";

// checkout actions
export const ADD_CHECKOUT_ITEM = "ADD_CHECKOUT_ITEM";
export const REMOVE_CHECKOUT_ITEM = "REMOVE_CHECKOUT_ITEM";
export const GET_CHECKOUT_TOTAL = "GET_CHECKOUT_TOTAL";
export const SET_CHECKOUT_ALL = "SET_CHECKOUT_ALL";
export const UNSET_CHECKOUT_ALL = "UNSET_CHECKOUT_ALL";
export const CHECK_CHECKOUT_ALL = "CHECK_CHECKOUT_ALL";

// filter actions
export const SET_LISTVIEW = "SET_LISTVIEW";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_SELECT_ALL = "SET_SELECT_ALL";

// sorting 
export const PRICE_SORT = "PRICE_SORT";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";

// blog actions
export const GET_SEARCH_RESULT_REQUEST = "GET_SEARCH_RESULT_REQUEST";
export const GET_SEARCH_RESULT_SUCCESS = "GET_SEARCH_RESULT_SUCCESS";
export const GET_SEARCH_RESULT_FAIL = "GET_SEARCH_RESULT_FAIL";